from __future__ import annotations

from collections import Counter
from html import escape
import json
from pathlib import Path

from .core import ScanResult


def write_json(result: ScanResult, path: str) -> None:
    Path(path).write_text(json.dumps(result.to_dict(), indent=2, ensure_ascii=False), encoding="utf-8")


def write_html(result: ScanResult, path: str) -> None:
    counts = Counter(f.severity.value for f in result.findings)
    rows = []
    for finding in result.findings:
        rows.append(
            "<tr>"
            f"<td>{escape(finding.severity.value.upper())}</td>"
            f"<td>{escape(finding.module)}</td>"
            f"<td>{escape(finding.title)}</td>"
            f"<td>{escape(finding.description)}</td>"
            f"<td><code>{escape(finding.evidence)}</code></td>"
            f"<td>{escape(finding.remediation)}</td>"
            "</tr>"
        )
    errors = "".join(f"<li>{escape(error)}</li>" for error in result.errors)
    html = f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>RieaZuka Report</title>
<style>body{{font-family:system-ui,sans-serif;max-width:1200px;margin:40px auto;padding:0 18px;line-height:1.45}}table{{border-collapse:collapse;width:100%}}th,td{{border:1px solid #ccc;padding:8px;text-align:left;vertical-align:top}}th{{background:#eee}}code{{overflow-wrap:anywhere}}.summary{{display:flex;gap:16px;flex-wrap:wrap}}.card{{border:1px solid #ccc;border-radius:8px;padding:10px 16px}}</style>
</head><body><h1>RieaZuka Security Audit</h1><p><strong>Target:</strong> {escape(result.target)}</p>
<div class="summary"><div class="card">High: {counts['high']}</div><div class="card">Medium: {counts['medium']}</div><div class="card">Low: {counts['low']}</div><div class="card">Info: {counts['info']}</div></div>
<h2>Findings</h2><table><thead><tr><th>Severity</th><th>Module</th><th>Finding</th><th>Description</th><th>Evidence</th><th>Remediation</th></tr></thead><tbody>{''.join(rows)}</tbody></table>
<h2>Errors</h2><ul>{errors}</ul><footer><p>Generated by RieaZuka 1.0.0. Authorized testing only.</p></footer></body></html>"""
    Path(path).write_text(html, encoding="utf-8")
